[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Custom Serial Monitor port
monitor_port = /dev/ttyUSB1

; Custom Serial Monitor speed (baud rate)
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient
    https://github.com/avishorp/TM1637.git#v1.2.0
    teckel12/NewPing