[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

[env:esp32cam]
board = esp32cam
upload_port = COM5 #USB
monitor_port = COM5
build_flags = -DCAMERA_MODEL_AI_THINKER

[env:esp32s3]
board = esp32-s3-devkitc-1
upload_port = COM6 #USB-C to UART
monitor_port = COM6
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_ESP32S3_EYE